# Generated by Django 5.0.2 on 2024-03-04 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        ('users', '0002_alter_techuser_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techuser',
            options={'ordering': ('username',)},
        ),
        migrations.AlterField(
            model_name='techuser',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tech_users', to='note.techtag'),
        ),
    ]
