# Generated by Django 5.0.2 on 2024-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='resource',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
