# Generated by Django 5.0.2 on 2024-03-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_note_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='resource',
            new_name='resources',
        ),
    ]
